// Mocks generated by Mockito 5.4.6 from annotations
// in safe_scan/test/features/home/presentation/cubits/scan_domain_cubit/scan_domain_cubit_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:mockito/mockito.dart' as _i1;
import 'package:safe_scan/features/scan/domain/entities/domain_response_model.dart'
    as _i2;
import 'package:safe_scan/features/scan/domain/repos/api_repo.dart' as _i3;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeDomainResponseModel_0 extends _i1.SmartFake
    implements _i2.DomainResponseModel {
  _FakeDomainResponseModel_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeData_1 extends _i1.SmartFake implements _i2.Data {
  _FakeData_1(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [ApiRepo].
///
/// See the documentation for Mockito's code generation for more information.
class MockApiRepo extends _i1.Mock implements _i3.ApiRepo {
  MockApiRepo() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<_i2.DomainResponseModel> fetchDomainReport(String? domain) =>
      (super.noSuchMethod(
            Invocation.method(#fetchDomainReport, [domain]),
            returnValue: _i4.Future<_i2.DomainResponseModel>.value(
              _FakeDomainResponseModel_0(
                this,
                Invocation.method(#fetchDomainReport, [domain]),
              ),
            ),
          )
          as _i4.Future<_i2.DomainResponseModel>);

  @override
  _i4.Future<_i2.DomainResponseModel> fetchFileReport(String? fileHash) =>
      (super.noSuchMethod(
            Invocation.method(#fetchFileReport, [fileHash]),
            returnValue: _i4.Future<_i2.DomainResponseModel>.value(
              _FakeDomainResponseModel_0(
                this,
                Invocation.method(#fetchFileReport, [fileHash]),
              ),
            ),
          )
          as _i4.Future<_i2.DomainResponseModel>);
}

/// A class which mocks [DomainResponseModel].
///
/// See the documentation for Mockito's code generation for more information.
class MockDomainResponseModel extends _i1.Mock
    implements _i2.DomainResponseModel {
  MockDomainResponseModel() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.Data get data =>
      (super.noSuchMethod(
            Invocation.getter(#data),
            returnValue: _FakeData_1(this, Invocation.getter(#data)),
          )
          as _i2.Data);

  @override
  List<Object?> get props =>
      (super.noSuchMethod(Invocation.getter(#props), returnValue: <Object?>[])
          as List<Object?>);

  @override
  Map<String, dynamic> toJson() =>
      (super.noSuchMethod(
            Invocation.method(#toJson, []),
            returnValue: <String, dynamic>{},
          )
          as Map<String, dynamic>);
}
