// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDsQAsfNx1vbTzWu3DFTKcx3JYEk5MzwbM',
    appId: '1:848680098744:web:cea1e70917a019c3cacd4d',
    messagingSenderId: '848680098744',
    projectId: 'safe-scan-17e7e',
    authDomain: 'safe-scan-17e7e.firebaseapp.com',
    storageBucket: 'safe-scan-17e7e.firebasestorage.app',
    measurementId: 'G-45QMLCNP5L',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB1fVkPgmLAV20jWJjjvSUR-JWlT4dbxn0',
    appId: '1:848680098744:android:0ab4406bd7463bf6cacd4d',
    messagingSenderId: '848680098744',
    projectId: 'safe-scan-17e7e',
    storageBucket: 'safe-scan-17e7e.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC1GWvjx6-VoyVUn78Hhnk-F0dXWXiQm2o',
    appId: '1:848680098744:ios:55ee4e46c78a3d66cacd4d',
    messagingSenderId: '848680098744',
    projectId: 'safe-scan-17e7e',
    storageBucket: 'safe-scan-17e7e.firebasestorage.app',
    iosBundleId: 'com.example.safeScan',
  );
}
